version: "3.9"

# MongoDB Cluster

# 1)
# 1.1) shard #1 - replica set #1, 3 nodes,
# 1.2) shard #2 - replica set #2, 3 nodes,
# 2) config server replicas - 3 nodes
# 3) 2 Mongos routers


#1.1) shard #1 - replica set #1, 3 nodes,
services:
  mongo_rs1_n1:
    container_name: mongo_rs1_n1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command:  mongod --auth --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command:  mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data1:/data/db

  mongo_rs1_n2:
    container_name: mongo_rs1_n2
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data2:/data/db

  mongo_rs1_n3:
    container_name: mongo_rs1_n3
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data3:/data/db

  # 1.2) shard #2 - replica set #2, 3 nodes,
  mongo_rs2_n1:
    container_name: mongo_rs2_n1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data4:/data/db

  mongo_rs2_n2:
    container_name: mongo_rs2_n2
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27057:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data5:/data/db

  mongo_rs2_n3:
    container_name: mongo_rs2_n3
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27067:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - mongo_cluster_data6:/data/db

  # 2) config server replicas - 3 nodes
  mongo_cfgrs_1:
    container_name: mongo_cfgrs_1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - config1:/data/db

  mongo_cfgrs_2:
    container_name: mongo_cfgrs_2
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - config2:/data/db

  mongo_cfgrs_3:
    container_name: mongo_cfgrs_3
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
#    command: mongod --auth --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017 --keyFile /keyfile/keyfile
    command: mongod --configsvr --replSet mongo_cfgrs --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro
      - config3:/data/db

  # 3) Mongos routers: 2pcs
  mongos_1:
    container_name: mongos_1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
    command: mongos --configdb mongo_cfgrs/mongo_cfgrs_1:27017,mongo_cfgrs_2:27017,mongo_cfgrs_3:27017 --port 27017 --bind_ip_all
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro

  mongos_2:
    container_name: mongos_2
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../.envs/.docker-compose-local/.mongo
    command: mongos --configdb mongo_cfgrs/mongo_cfgrs_1:27017,mongo_cfgrs_2:27017,mongo_cfgrs_3:27017 --port 27017 --bind_ip_all
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - keyfile:/keyfile
      - /etc/localtime:/etc/localtime:ro

volumes:
  keyfile: { }
  config1: { }
  config2: { }
  config3: { }
  mongo_cluster_data1: { }
  mongo_cluster_data2: { }
  mongo_cluster_data3: { }
  mongo_cluster_data4: { }
  mongo_cluster_data5: { }
  mongo_cluster_data6: { }
