#!/bin/bash

set -o errexit # if any command fails any reason, script fails
set -o pipefail # if none of of you pipecommand fails, exit fails
set -o nounset # if none of variables set, exit


postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

exec "$@"
