#!/bin/bash

python3 -m scripts.migrate
python3 -m scripts.create_permissions_roles
gunicorn main:app --bind "${API_AUTH_HOST}:${API_AUTH_PORT}" --reload --workers=2 --timeout=300 --worker-class uvicorn.workers.UvicornWorker