version: "3.9"

services:
    elasticsearch:
      build:
        context: .
        dockerfile: elasticsearch/Dockerfile
      container_name: elasticsearch
      env_file:
        - ../../.envs/.docker-compose-local/.elk/.elastic
      ports:
        - 9200:9200
      volumes:
        - elastic_data:/tmp/elasticsearch/data
      networks:
        - local_network

    kibana:
      build:
        context: .
        dockerfile: kibana/Dockerfile
      container_name: kibana
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - local_network

    logstash:
      build:
        context: .
        dockerfile: logstash/Dockerfile
      container_name: logstash
      env_file:
        - ../../.envs/.docker-compose-local/.elk/.logstash
        - ../../.envs/.docker-compose-local/.elk/.elastic
      ports:
        - "5044:5044/udp"
      command: logstash -f /config/logstash.conf
      depends_on:
        - elasticsearch
      networks:
        - local_network
        - shared_network

volumes:
  elastic_data:

networks:
  local_network:
    driver: bridge
  shared_network:
    external: true
