version: "3.9"

services:
  clickhouse_ugc:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: clickhouse_ugc
    env_file:
      - ../../.envs/.docker-compose-local/.clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - shared_network
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:

networks:
  shared_network:
    external: true